### ISSUE TITLE
Db Xref for https://search.proquest.com/

### ISSUE THREAD

**Issue by cooperl09** [Planteome/go-site-xrefs-fork#1]
We have a number of new terms which were taken from a thesis, which is found here:
https://search.proquest.com/docview/1426182399
Would it be possible to create a db xref for this database?  
Any other suggestions? Could not find any other place to link these to.
@elserj @austinmeier

**Comment by austinmeier** [comment]
added stanza in commit:
6122c57f922756841b1027962b9a723663f13998

Use PROQUEST:[sample_id]  namespace.

The id for that particular thesis would be `PROQUEST:1426182399`

**Comment by austinmeier** [comment]
Merge may not be accepted.  Chris and Seth recommend simply using the URL:  https://github.com/geneontology/go-site/pull/407

**Comment by cooperl09** [comment]
We decided to just use the URL in this case. If we get more refs from this source, we can revisit.
See https://github.com/geneontology/go-site/pull/407
